# Working with multiple data sets

There are two data files that we'll be working with for this week's assignment.  They are described below.  Load those data files in with Pandas and then work to answering each of the questions below.

## npidata.csv

This file is basic information about every healthcare provider in the US.  It has one row for each NPI (National Provider Identifier).  It contains information such as the provider's name and address.


## cmsYYYY.csv

These are files about what kinds of procedures and patients providers in the US are serving under CMS programs, Medicare and Medicaid.  Each contains various statistics about providers over the course of a year.  There are three of these, for the years 2014, 2015, and 2016.  These files, however, don't contain information about the provider such as where the provider is located.

## Our Goals

For this assignment, we're going to want to compute some statistics based on the data in the **cms** files, but aggregate that data based on information in the **npidata** file.  As in last week's assignment, you'll need to store your answers in a variable called `answer` at the end of each step.

In [2]:
import pandas as pd

## Part 1

In this first step, we'll need to merge together all of the **cms** files into a single dataframe.  Be careful that these files might not be identical, so you'll have to look a little bit to figure out how to merge them.

As you are merging them, make sure that you retain information about which file (i.e. which year) the data came from.  Call that new columns `year`.

In your `answer` variable, provide a complete data frame that contains all of the rows and columns from the **cms** files, plus an additional column to store the year/file that particular row came from.

The assertion tests will give you a good idea as to if you're merging the files correctly.

In [3]:
### SOLUTION
cms_2014= pd.read_csv('/data/cms2014.csv')
cms_2015= pd.read_csv('/data/cms2015.csv')
cms_2016= pd.read_csv('/data/cms2016.csv')
cms_2014.insert(0, 'year', 2014, True)
cms_2014.columns=map(str.lower, cms_2014.columns)
cms_2015.insert(0, 'year', 2015, True)
cms_2015.columns=map(str.lower, cms_2015.columns)
cms_2016.insert(0, 'year', 2016, True)
cms_2016.columns=map(str.lower, cms_2016.columns)
answer= pd.concat([cms_2014, cms_2015, cms_2016])

In [4]:
assert(answer.shape == (193862, 60))
assert(list(answer['year'].unique()) == [2014,2015,2016])
assert(set(answer.columns.str.lower()) == set(['year', 'nbr', 'npi', 'provider_type',
       'medicare_participation_indicator', 'number_of_hcpcs', 'total_services',
       'total_unique_benes', 'total_submitted_chrg_amt',
       'total_medicare_allowed_amt', 'total_medicare_payment_amt',
       'total_medicare_stnd_amt', 'drug_suppress_indicator',
       'number_of_drug_hcpcs', 'total_drug_services',
       'total_drug_unique_benes', 'total_drug_submitted_chrg_amt',
       'total_drug_medicare_allowed_amt', 'total_drug_medicare_payment_amt',
       'total_drug_medicare_stnd_amt', 'med_suppress_indicator',
       'number_of_med_hcpcs', 'total_med_services', 'total_med_unique_benes',
       'total_med_submitted_chrg_amt', 'total_med_medicare_allowed_amt',
       'total_med_medicare_payment_amt', 'total_med_medicare_stnd_amt',
       'beneficiary_average_age', 'beneficiary_age_less_65_count',
       'beneficiary_age_65_74_count', 'beneficiary_age_75_84_count',
       'beneficiary_age_greater_84_count', 'beneficiary_female_count',
       'beneficiary_male_count', 'beneficiary_race_white_count',
       'beneficiary_race_black_count', 'beneficiary_race_api_count',
       'beneficiary_race_hispanic_count', 'beneficiary_race_natind_count',
       'beneficiary_race_other_count', 'beneficiary_nondual_count',
       'beneficiary_dual_count', 'beneficiary_cc_afib_percent',
       'beneficiary_cc_alzrdsd_percent', 'beneficiary_cc_asthma_percent',
       'beneficiary_cc_cancer_percent', 'beneficiary_cc_chf_percent',
       'beneficiary_cc_ckd_percent', 'beneficiary_cc_copd_percent',
       'beneficiary_cc_depr_percent', 'beneficiary_cc_diab_percent',
       'beneficiary_cc_hyperl_percent', 'beneficiary_cc_hypert_percent',
       'beneficiary_cc_ihd_percent', 'beneficiary_cc_ost_percent',
       'beneficiary_cc_raoa_percent', 'beneficiary_cc_schiot_percent',
       'beneficiary_cc_strk_percent', 'beneficiary_average_risk_score']))

,year,nbr,npi,provider_type,medicare_participation_indicator,number_of_hcpcs,total_services,total_unique_benes,total_submitted_chrg_amt,total_medicare_allowed_amt,...,beneficiary_cc_depr_percent,beneficiary_cc_diab_percent,beneficiary_cc_hyperl_percent,beneficiary_cc_hypert_percent,beneficiary_cc_ihd_percent,beneficiary_cc_ost_percent,beneficiary_cc_raoa_percent,beneficiary_cc_schiot_percent,beneficiary_cc_strk_percent,beneficiary_average_risk_score
0,2014,1,1003000134,Pathology,Y,13,8643.0,4276,1357139.00,321641.88,...,12.0,20.0,53.0,57.0,28.0,9.0,37.0,1.0,3.0,1.0007
1,2014,19,1003001249,Physical Therapist,Y,4,1221.0,69,88686.28,34060.09,...,NaN,39.0,64.0,75.0,32.0,NaN,68.0,NaN,NaN,1.1912
2,2014,21,1003001322,Mass Immunization Roster Biller,Y,7,788.0,370,21640.24,21634.91,...,13.0,18.0,42.0,49.0,24.0,5.0,25.0,NaN,3.0,0.8019
3,2014,37,1003002486,Chiropractic,Y,2,142.0,22,7458.44,5037.51,...,NaN,NaN,59.0,59.0,NaN,0.0,64.0,0.0,0.0,0.7920
4,2014,73,1003005430,Clinical Psychologist,Y,3,130.0,11,20640.00,14968.22,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.9718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63088,2014,986611,1992995542,Ophthalmology,Y,38,2373.0,569,724714.00,357091.04,...,10.0,58.0,55.0,75.0,39.0,7.0,52.0,NaN,7.0,1.6501
63089,2014,986618,1992996219,Neurology,Y,17,412.0,222,204170.00,66712.22,...,34.0,26.0,45.0,55.0,33.0,7.0,28.0,12.0,19.0,1.6241
63090,2014,986619,1992996284,Family Practice,Y,10,221.0,112,38869.00,15237.32,...,13.0,58.0,59.0,75.0,37.0,NaN,44.0,NaN,NaN,1.0674
63091,2014,986622,1992996458,Sleep Medicine,Y,27,1625.0,562,310966.00,130729.39,...,43.0,38.0,65.0,75.0,56.0,6.0,47.0,8.0,28.0,1.4831
63092,2014,986637,1992997175,Rheumatology,Y,33,677.0,208,129621.70,52185.62,...,34.0,28.0,47.0,60.0,29.0,14.0,75.0,NaN,NaN,1.4396

## Part 2

In this next part, we're going to join the **cms** data with the provider information in the **/data/npidata.csv** file.  In this join, we don't want to lose any records from the **cms** files, even if no matching provider exists in the **npidata** file.  However, we don't care about any providers from the **npidata** file that don't have records in the **cms** files.  Those providers can be ignored.

Join the data files together to create one unified data frame called `answer`.  This dataframe should have all the columns from both **cms** and **npidata** files, joined together using the `npi` column.  

Note that `npi` is unique in the **npidata** file.

In [ ]:
### SOLUTION
import pandas as pd
cms_2014= pd.read_csv('/data/cms2014.csv')
cms_2015= pd.read_csv('/data/cms2015.csv')
cms_2016= pd.read_csv('/data/cms2016.csv')
cms_2014.insert(0, 'year', 2014, True)
cms_2014.columns=map(str.lower, cms_2014.columns)
cms_2015.insert(0, 'year', 2015, True)
cms_2015.columns=map(str.lower, cms_2015.columns)
cms_2016.insert(0, 'year', 2016, True)
cms_2016.columns=map(str.lower, cms_2016.columns)
answer= pd.concat([cms_2014, cms_2015, cms_2016])
npi= pd.read_csv('/data/npidata.csv')
cols = list(npi.columns)
a, b = cols.index('row'), cols.index('NPI')
cols[b], cols[a] = cols[a], cols[b]
npi = npi[cols]
cols = list(answer.columns)
a, c = cols.index('year'), cols.index('npi')
cols[c], cols[a] = cols[a], cols[c]
answer = answer[cols]
npi=npi.drop('row', axis=1)
answer=pd.merge(left=answer, right=npi, how='left', left_on='npi', right_on='NPI', indicator=True)

In [ ]:
import numpy
assert(answer.shape == (193862, 103))
assert(list(answer['Provider Business Mailing Address State Name'].unique()) == ['IL','MO',numpy.nan,'WY'])
assert(list(answer.groupby('Provider Business Mailing Address State Name').NPI.count()) == [111520, 53366, 4805])

## Part 3

If you did everything right above, you'll notice that grouping by a column with NaN in it will cause some rows to disappear from the aggregation test.  So, let's create a new column called `'State'` that has the same value as whatever is in the `'Provider Business Mailing Address State Name'` column or a value of `'XX'` if there is no state information.

Set `answer` to be your final data frame with the new `'State'` column added.

In [ ]:
### SOLUTION
import numpy
answer['State']=answer['Provider Business Mailing Address State Name']
answer['State'] = answer['State'].replace(numpy.NaN, 'XX')

In [ ]:
assert(list(answer.groupby('State').npi.count()) == [111520, 53366, 4805, 24171])
assert(answer.shape == (193862, 104))

## Part 4

Next, let's summarize the data by year and by State.  Create a pivot table that contains one row for each state and one column for each year.  Within the pivot table, put a sum of total services as the values.

Assign `answer` to be that resulting pivot table.  In the tests, I'm going to plot a bar chart of your pivot table.

In [ ]:
%matplotlib inline
### SOLUTION
by_state = answer.groupby(['State','year'])['total_services'].sum().reset_index()
answer=by_state.pivot(index='State', columns='year', values='total_services')

In [ ]:
by_state

In [ ]:
assert(answer.shape == (4,3))
assert(answer.sum().sum() == 519185664.6999999)
assert(answer[2016].sum() == 176596933.80000004)
assert(answer.loc['WY'].sum() == 10892707.4)

In [ ]:
%matplotlib inline
answer.plot.bar()